# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - techkrishi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_1d253eb9349445238df03c58b42df3b4 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4c5c7567802a46f4895562bc6975e00e }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_1d253eb9349445238df03c58b42df3b4 }}/dhanu:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'techkrishi'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a413c59f735b4c2c94e2667cadc6f7f2 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_1d253eb9349445238df03c58b42df3b4 }}/dhanu:${{ github.sha }}'